### PR TITLE
chore(PPDSC-1866): remove crop config

### PR DESCRIPTION
**Pull request by mstuartf**
[PPDSC-1866](https://nidigitalsolutions.jira.com/browse/PPDSC-1866)

**What**

1. Background - why this is needed
- cropConfig and cropAdjustments deprecated in favour of fontMetrics
2. What did you do
- Removed all references to cropConfig and cropAdjustments
3. What does the reviewers should expect
- Users should see a console warning if using js (or a compilation error if using ts)

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

[PPDSC-1866]: https://nidigitalsolutions.jira.com/browse/PPDSC-1866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pp-serviceaccount** [comment]
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-1866-deprecated-crop-config
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-1866-deprecated-crop-config/storybook

**Review by mutebg — DISMISSED** [review]

**Review by JohnTParsons — APPROVED** [review]

**Comment by Vanals** [comment]
1)
I have found still some comments referring to old code

`   /* * Following code to be removed once only Font Metrics will be supported by newsKit`

Maybe we can replace it with something saying the code  in between

// COMMENT

//**

is only for warning. Even tho we could remove even any warning imo we do not support it anymore.

2) Storybook is broken 🙏  , check the console log. Is something about line height value.
Also I would suggest to go through design review, just to double check the textcropping looks good **also** from their side

Screenshot 2023-02-14 at 15 31 13

**Comment by mstuartf** [comment]
@Vanals I can't recreate the Storybook issue locally or on the remote env:

Screenshot 2023-02-15 at 09 48 55
Screenshot 2023-02-15 at 09 49 12

There's the usual console noise but the app loads fine and no errors to do with line height.

**Comment by mstuartf** [comment]
I've clicked through every component and can't see those errors. What's strange is this is the code that throws it:

Screenshot 2023-02-15 at 09 57 50

**Review by mutebg — APPROVED** [review]

**Comment by mstuartf** [comment]
The `lineHeight` issue is unrelated to this PR and a separate fix has been merged into main. Design have signed off on the changes.

**Review by Xin00163 — APPROVED** [review]

**Review by JohnTParsons — APPROVED** [review]

**Pull request merged**
