### PR TITLE
fix(747): hide version on home page

### PR DESCRIPTION
**Pull request by mstuartf**
#747 

**What**

1. Background - why this is needed
- Version update causing visual tests to fail
2. What did you do
- hide version number on home page visual tests
Screenshot 2023-03-28 at 11 52 15

3. What does the reviewers should expect
- visual tests should pass when version changes

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

### CODE REVIEW

**Comment by pp-serviceaccount** [comment]
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/747-percy-css
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/747-percy-css/storybook

**Review by JohnTParsons — APPROVED** [review]
Looks good

**Review by mutebg — APPROVED** [review]
The only thing is the branch name should start with `docs` so that this not end up in the wrong release notes section.

**Comment by mstuartf** [comment]
> The only thing is the branch name should start with `docs` so that this not end up in the wrong release notes section.

It's a pipeline fix rather than a change to the docs. Not sure which is best.

**Pull request closed without merging**
