### PR TITLE
fix: add new sample mp3s for e2e tests and storybook

### PR DESCRIPTION
**Pull request by lhaggar**
**What**
Previous mp3 test files used in Storybook and E2E tests has been removed, meaning E2E tests fail. This PR updates references to a new file, which will be self-hosted under the newskit.co.uk website. This PR will require forced merging with broken E2E and deploying through to prod. Subsequent builds should then work as normal.

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

### CODE REVIEW

**Comment by pp-serviceaccount** [comment]
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/new-sample-mp3s-for-e2e
  Storybook: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/new-sample-mp3s-for-e2e/storybook

**Review by JohnTParsons — APPROVED** [review]

**Review by pdimova — DISMISSED** [review]
Just wondering what the reason is for removing these files on S3

**Comment by lhaggar** [comment]
@pdimova not 100% sure. The bucket exists but is empty. It's in the NGN dev account rather than NewsKit's, I think its the original bucket before the site origin was moved.

**Comment by JohnTParsons** [comment]
> @pdimova not 100% sure. The bucket exists but is empty. It's in the NGN dev account rather than NewsKit's, I think its the original bucket before the site origin was moved.

I thought I'd moved the ncu-newskit-docs bucket from NGN to product platforms account a year ago. Not sure.

I thought NGN was just being used to save the Terraform state.

**Review by kboeff — APPROVED** [review]

**Pull request merged**
