### PR TITLE
docs(PPDSC-2805): update Ordered list component storybook scenarios

### PR DESCRIPTION
**Pull request by evgenitsn**
PPDSC-2805

**What**

1. Background - updating Storybook scenarios
2. What did you do - updated Ordered list scenarios
3. What does the reviewers should expect - new Ordered list scenarios in storybook

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [ ] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [ ] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**
image

**After:**
image

**Who should review this PR:**

**How to test:**

### CODE REVIEW

**Comment by pp-serviceaccount** [comment]
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2805-update-ordered-list-component-storybook-scenarios
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2805-update-ordered-list-component-storybook-scenarios/storybook

**Review by JohnTParsons — APPROVED** [review]

**Comment by JohnTParsons** [comment]
I thought I had replaced "5. echo" with a couple of long sentences to prove that paragraphs were indented correctly but that change seems to have disappeared at some point?!

**Comment by JohnTParsons** [comment]
@evgenitsn In this PR might it might be worth introducing the Storybook changes I made in https://github.com/newscorp-ghfb/newskit/pull/612 that seem to have got lost?

**Review by JohnTParsons — COMMENTED** [review]
I thought I had replaced "5. echo" with a couple of long sentences to prove that paragraphs were indented correctly but that change seems to have disappeared at some point?!

@evgenitsn In this PR might it might be worth introducing the Storybook changes I made in https://github.com/newscorp-ghfb/newskit/pull/612?

**Comment by JohnTParsons** [comment]
Ah, my changes are in the v7 branch, not in main, so that explains why not showing on this PR.

**Review by mstuartf — APPROVED** [review]

**Pull request merged**
