### PR TITLE
docs(PPDSC-2190): Patterns telephone number and input components pages

### PR DESCRIPTION
**Pull request by Srinivasan-Ramasamy**
PPDSC-2190

**What**

1. Telephone number doc page UI - http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2190-patterns-telephonenumber-inputcomponents-pages/patterns/forms/telephone-number/
2. Input components doc page UI - http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2190-patterns-telephonenumber-inputcomponents-pages/patterns/forms/input-components/
3. Fix for theme overview page border Illustration missing - http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2190-patterns-telephonenumber-inputcomponents-pages/theme/overview/

**I have done:**
- [X] Written unit tests against changes
- [X] Written functional tests against the component and/or NewsKit site
- [X] Updated relevant documentation

**I have tested manually:**
- [X] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [X] The screen reader reads and flows through the elements as expected.
- [X] There are no new errors in the browser console coming from this PR.
- [X] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

image

image

**After:**

image

image

**Who should review this PR:**

Doc Site.

**How to test:**

http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2190-patterns-telephonenumber-inputcomponents-pages/patterns/forms/telephone-number/

http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2190-patterns-telephonenumber-inputcomponents-pages/patterns/forms/input-components/

http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2190-patterns-telephonenumber-inputcomponents-pages/theme/overview/

### CODE REVIEW

**Comment by newskit-engineering** [comment]
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2190-patterns-telephonenumber-inputcomponents-pages
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2190-patterns-telephonenumber-inputcomponents-pages/storybook

**Review by evgenitsn — APPROVED** [review]

**Review by evgenitsn — COMMENTED** [review]
Sorry, approved by mistake.

**Comment by Srinivasan-Ramasamy** [comment]
> Sorry, approved by mistake.

No problem @evgenitsn, Thanks. Let me discuss with design team to get design approval for this and then will reach.

**Review by evgenitsn — APPROVED** [review]
Nice work!

**Comment by Srinivasan-Ramasamy** [comment]
Thanks @evgenitsn for taking the time to review :+1:

**Review by mstuartf — APPROVED** [review]

**Pull request merged**
