### PR TITLE
feat(ppdsc-2658):add styled component name to classname for debugging

### PR DESCRIPTION
**Pull request by LukeFinch**
PPDSC-2658

**What**

**Background - why this is needed**
Styled component elements do not have a recognisable className, therefore you will end up switching between React element tree and DevTools DOM tree when debugging.

**What did you do**
Add emotion compiler options to nextjs config.

**What does the reviewers should expect**
Development builds should show the component name in the class of exported style components.

image

**I have done:**
- [ ] Written unit tests against changes
- [ ] Written functional tests against the component and/or NewsKit site
- [ ] Updated relevant documentation

**I have tested manually:**
- [x] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
- [ ] The screen reader reads and flows through the elements as expected.
- [x] There are no new errors in the browser console coming from this PR.
- [ ] When visual test is not added, it renders correctly on different browsers and mobile viewports (Safari, Firefox, small mobile viewport, tablet)
- [ ] The Playground feature is working as expected

**Before:**

**After:**

**Who should review this PR:**

**How to test:**

### CODE REVIEW

**Comment by newskit-engineering** [comment]
You can preview these changes on:
  Documentation Site: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2658-add-styled-component-name-to-classname
  Storybook: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2658-add-styled-component-name-to-classname/storybook

**Review by mutebg — COMMENTED** [review]
Looks like as nice improvement, can we make it work on `src` folder as well? or that will cause lots of inconsistencies?

**Comment by LukeFinch** [comment]
> Looks like as nice improvement, can we make it work on `src` folder as well? or that will cause lots of inconsistencies?

It's part of the nextjs build process - that it automatically adds in the names in for debugging. So would only build anything in `/site/`

I need to remove the packages I added when testing. - they work with styled-components not emotion

Also because we re-export `styled` from emotion - we have to set an import map. This looked to cause some incompatibility with other possibilities - e.g a babel plugin.


One option we do have for adding component names into the class name is to use the 'label' property on any styled components

```
const MyDiv = styled.div`
  label: custom-debugging-label;
  height: 150px;
  background: red;
`;
```

**Review by mutebg — COMMENTED** [review]
wondering why yarn.lock is updated without updating anything in package.json?

**Review by JohnTParsons — APPROVED** [review]

**Comment by LukeFinch** [comment]
> wondering why yarn.lock is updated without updating anything in package.json?

Ah - I added and then removed a package when trying some things out. Will remove yarn .ock

**Review by JohnTParsons — APPROVED** [review]

**Review by mutebg — APPROVED** [review]

**Pull request merged**
